### ISSUE TITLE
[Request] Spine 2D support!

### ISSUE THREAD

**Issue by JaredSartin** [gogoprog/gengine-old#48]
Hey,

Been playing around with your engine and it meets much of the needs I have - except 1: Spine 2D support. My animators use Spine 2D and I would love to give this engine a shot an upcoming game!

Cheers

**Comment by gogoprog** [comment]
All right, added to the Hot Todo list !

Thanks for using gengine ;)

**Comment by JaredSartin** [comment]
Awesome! If I get some time between projects, I will see what I can do to help on it.
