### ISSUE TITLE
Mac Build

### ISSUE THREAD

**Issue by JaredSartin** [gogoprog/gengine-old#55]
Hey,

Wondering if a Mac build process will be coming in the near future? I would love to push this tool for web games at work, but my team uses Macs.

**Comment by gogoprog** [comment]
Hello,

I'm currently on a huge refactor of the engine that I need to finish first, but then I can work the Mac support.

So yes, let's say it will be done within a month ;)

**Comment by JaredSartin** [comment]
Awesome! Glad to see you are supporting the engine so much! Let me know where I can help. I run Mac mainly, but I can spin up Windows or Linux. Loving where this is going.
